export enum NotificationType {
  REFER = 'REFER',
  COMMENTED = 'COMMENTED',
  LIKED_POST = 'LIKED_POST',
  NEW_RAFFLE = 'NEW_RAFFLE',
  RAFFLE_DRAW = 'RAFFLE_DRAW',
  MATCH_RESULT = 'MATCH_RESULT',
  LIKED_COMMENT = 'LIKED_COMMENT',
  REFERRAL_BONUS = 'REFERRAL_BONUS',
  REPLIED_COMMENT = 'REPLIED_COMMENT',
  USE_REFERRAL_CODE = 'USE_REFERRAL_CODE',
  STARTED_FOLLOWING = 'STARTED_FOLLOWING',
  _12_HOUR_BEFORE_RAFFLE_DRAW = '_12_HOUR_BEFORE_RAFFLE_DRAW',
  DAILY_ACCUMULATED_POINT_NOTICE = 'DAILY_ACCUMULATED_POINT_NOTICE'
}

export enum RaffleEntryStatusType {
  WON = 'WON',
  LOST = 'LOST',
  PENDING = 'PENDING'
}

export enum RaffleStatusInterface {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED'
}

export enum RewardPointType {
  SHOP = 'SHOP',
  CHAT = 'CHAT',
  CHEER = 'CHEER',
  REFER = 'REFER',
  ENGAGE = 'ENGAGE',
  CREATOR = 'CREATOR',
  CONNECT = 'CONNECT',
  EXPRESS = 'EXPRESS',
  WELCOME = 'WELCOME',
  PRACTICE = 'PRACTICE',
  INFORMED = 'INFORMED',
  CASH_OUT = 'CASH_OUT',
  INFLUENCE = 'INFLUENCE',
  REFERRAL_BONUS = 'REFERRAL_BONUS',
  USE_REFERRAL_CODE = 'USE_REFERRAL_CODE'
}
